### PR TITLE
Fixes #23

### LINKED ISSUE #23: Read Data Task for Log / Analysis Page
Bring data from local storage, display at log/analysis page

### PR DESCRIPTION
**Pull request by LinhNguyen9**
Implementing log page display

### CODE REVIEW

**Review by melvyn9 — CHANGES_REQUESTED** [review]
The committed files did not pass the ESLint tests. Please correct it and then commit again.

**Review by joyceweng — APPROVED** [review]

**Review by MichaelRuddy — COMMENTED** [review]
Opened up this branch with live server and nothing is working, this branch is using an old version of the homepage, log page team should have pulled first, then added their changes. I need more info from log team and Melvyn

**Review by MichaelRuddy — APPROVED** [review]
Good work taking care of max tasks, making sure all ESLint tests passed, and popup looks good as well

**Review by mogeritz — APPROVED** [review]
Good work. Max Tasks to one hundred seems large enough, good fixes

**Review by melvyn9 — APPROVED** [review]

**Review by TiyaZhan — APPROVED** [review]

**Review by mogeritz — CHANGES_REQUESTED** [review]
Please Revert your changes to html file paths as well as other file paths, as this will otherwise clash with the github pages setup

**Review by mogeritz — CHANGES_REQUESTED** [review]
Also, I see that you removed the calculation of a time difference, why is that? We require this functionality in our code for analytics.

**Comment by mogeritz** [comment]
Merging this branch will be very dangerous, as since it was opened, there were multiple changes to main. If we merge this request without first remerging main into this branch, we risk losing a bunch of functionality that has been added since this branch was created. I would strongly advise the log team to recheck for this circumstance.

**Comment by melvyn9** [comment]
@mogeritz Regarding your comments should I

1. Add back all the . in front of all the scripts? For example ./styles/mystyle.css?
2. For the time difference there were merge conflicts and the log team deleted it so I just accepted their code to solve the conflict. I can just add it back since they did not use it.

Are these the issues I need to address?

**Review by mogeritz — APPROVED** [review]

**Pull request merged**
